const { db} = require('../../src/utils/dbUtil')
const app = require('../../loanservice')
const request = require('supertest')
const { beforeAllFN, afterAllFN } = require('../helpers/helpers')
describe('check the api request of loanroute', () => {
    beforeAllFN(db)
    it('/ifscValidate/:ifscCode', async () => {
        let response = await request(app).get('/loan-service/api/v1/ifscValidate/ICIC0000057')
        expect(response.body.status).toEqual('success')
        expect(response.statusCode).toBe(200)
        expect(response.body).toHaveProperty('message')
        expect(response.body.message).toHaveProperty('NEFT')
        expect(response.body.message).toHaveProperty('RTGS')
        expect(response.body.message).toHaveProperty('UPI')
        expect(response.body.message).toHaveProperty('DISTRICT')
        expect(response.body.message).toHaveProperty('CITY')
        expect(response.body.message).toHaveProperty('CONTACT')
        expect(response.body.message).toHaveProperty('ISO3166')
        expect(response.body.message).toHaveProperty('IMPS')
        expect(response.body.message).toHaveProperty('ADDRESS')
        expect(response.body.message).toHaveProperty('MICR')
        expect(response.body.message).toHaveProperty('CENTRE')
        expect(response.body.message).toHaveProperty('SWIFT')
        expect(response.body.message).toHaveProperty('STATE')
        expect(response.body.message).toHaveProperty('BANK')
        expect(response.body.message).toHaveProperty('BANKCODE')
        expect(response.body.message).toHaveProperty('IFSC')
        expect(response.body).toHaveProperty('paymentModes')
        expect(response.body.paymentModes).toHaveProperty('netBanking')
        expect(response.body.paymentModes).toHaveProperty('debitCard')
    })
    afterAllFN(db)
})